jobs:
  build:
    machine: true
    steps:
      - checkov/scan:
          api-key: 6bridgecrew-9example-2api-key1-demo9
          directory: ./terragoat
          output: json

orbs:
  checkov: bridgecrew/checkov-orb@0.0.3
version: 2.1
